theme: jekyll-theme-tactile
title: Welcome to Astrophe's homepage!
description: Feel free to bookmark this page to keep an eye on my project updates
<h2>The project</h2>
<p>Python module for scraping pdfs. 
Table lines are overlooked in current software.
Therefore information is grouped according to the position of text.
Detecting the postion of table lines would assist in certain cases e.g. pdfs which have two rows of column-headers.
</p>

